{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "hvoxQZdF4G2E"
      },
      "outputs": [],
      "source": [
        "# step_001 - no control at all\n",
        "# step_002 - stand up reward and parallel feet penalty\n",
        "# step_003 - step_002 and forward reward\n",
        "# step_004 - step_003 and control penalty, knee flex reward and foot up reward\n",
        "# step_007 - stand up reward only\n",
        "# step_008 - step_007 and forward reward\n",
        "\n",
        "current_step = 'step_008'"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "K3asHLR1_a5J",
        "outputId": "9ceaf949-c5d3-443f-f085-06b18fcfaaeb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Reading package lists... Done\n",
            "Building dependency tree... Done\n",
            "Reading state information... Done\n",
            "cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).\n",
            "ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).\n",
            "xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.15).\n",
            "Suggested packages:\n",
            "  libgle3 python3-numpy python3-tk swig-doc swig-examples swig4.0-examples\n",
            "  swig4.0-doc\n",
            "The following NEW packages will be installed:\n",
            "  freeglut3 libglu1-mesa python3-opengl swig swig4.0\n",
            "0 upgraded, 5 newly installed, 0 to remove and 35 not upgraded.\n",
            "Need to get 1,940 kB of archives.\n",
            "After this operation, 13.6 MB of additional disk space will be used.\n",
            "Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 freeglut3 amd64 2.8.1-6 [74.0 kB]\n",
            "Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglu1-mesa amd64 9.0.2-1 [145 kB]\n",
            "Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 python3-opengl all 3.1.5+dfsg-1 [605 kB]\n",
            "Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 swig4.0 amd64 4.0.2-1ubuntu1 [1,110 kB]\n",
            "Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 swig all 4.0.2-1ubuntu1 [5,632 B]\n",
            "Fetched 1,940 kB in 3s (769 kB/s)\n",
            "Selecting previously unselected package freeglut3:amd64.\n",
            "(Reading database ... 126374 files and directories currently installed.)\n",
            "Preparing to unpack .../freeglut3_2.8.1-6_amd64.deb ...\n",
            "Unpacking freeglut3:amd64 (2.8.1-6) ...\n",
            "Selecting previously unselected package libglu1-mesa:amd64.\n",
            "Preparing to unpack .../libglu1-mesa_9.0.2-1_amd64.deb ...\n",
            "Unpacking libglu1-mesa:amd64 (9.0.2-1) ...\n",
            "Selecting previously unselected package python3-opengl.\n",
            "Preparing to unpack .../python3-opengl_3.1.5+dfsg-1_all.deb ...\n",
            "Unpacking python3-opengl (3.1.5+dfsg-1) ...\n",
            "Selecting previously unselected package swig4.0.\n",
            "Preparing to unpack .../swig4.0_4.0.2-1ubuntu1_amd64.deb ...\n",
            "Unpacking swig4.0 (4.0.2-1ubuntu1) ...\n",
            "Selecting previously unselected package swig.\n",
            "Preparing to unpack .../swig_4.0.2-1ubuntu1_all.deb ...\n",
            "Unpacking swig (4.0.2-1ubuntu1) ...\n",
            "Setting up freeglut3:amd64 (2.8.1-6) ...\n",
            "Setting up libglu1-mesa:amd64 (9.0.2-1) ...\n",
            "Setting up swig4.0 (4.0.2-1ubuntu1) ...\n",
            "Setting up swig (4.0.2-1ubuntu1) ...\n",
            "Setting up python3-opengl (3.1.5+dfsg-1) ...\n",
            "Processing triggers for libc-bin (2.35-0ubuntu3.8) ...\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link\n",
            "\n",
            "/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link\n",
            "\n",
            "Processing triggers for man-db (2.10.2-1) ...\n",
            "Collecting pyvirtualdisplay\n",
            "  Downloading PyVirtualDisplay-3.0-py3-none-any.whl.metadata (943 bytes)\n",
            "Requirement already satisfied: imageio[ffmpeg] in /usr/local/lib/python3.12/dist-packages (2.37.0)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]) (2.0.2)\n",
            "Requirement already satisfied: pillow>=8.3.2 in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]) (11.3.0)\n",
            "Requirement already satisfied: imageio-ffmpeg in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]) (0.6.0)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]) (5.9.5)\n",
            "Downloading PyVirtualDisplay-3.0-py3-none-any.whl (15 kB)\n",
            "Installing collected packages: pyvirtualdisplay\n",
            "Successfully installed pyvirtualdisplay-3.0\n"
          ]
        }
      ],
      "source": [
        "!apt install swig cmake ffmpeg xvfb python3-opengl\n",
        "!pip install pyvirtualdisplay imageio[ffmpeg]"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "V5Uw6AIK_eBr",
        "outputId": "b4818969-39cb-4038-869a-7979f64c0e21"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "env: MUJOCO_GL=egl\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<pyvirtualdisplay.display.Display at 0x79c39818bc20>"
            ]
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "import os\n",
        "\n",
        "NVIDIA_ICD_CONFIG_PATH = '/usr/share/glvnd/egl_vendor.d/10_nvidia.json'\n",
        "if not os.path.exists(NVIDIA_ICD_CONFIG_PATH):\n",
        "  with open(NVIDIA_ICD_CONFIG_PATH, 'w') as f:\n",
        "    f.write(\"\"\"{\n",
        "    \"file_format_version\" : \"1.0.0\",\n",
        "    \"ICD\" : {\n",
        "        \"library_path\" : \"libEGL_nvidia.so.0\"\n",
        "    }\n",
        "}\n",
        "\"\"\")\n",
        "\n",
        "%env MUJOCO_GL=egl\n",
        "\n",
        "from pyvirtualdisplay import Display\n",
        "virtual_display = Display(visible=0, size=(1920, 1080))\n",
        "virtual_display.start()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "dZAbUian_NS7",
        "outputId": "c7112cca-b8a7-43a0-dcd1-34df1fdf4ce5"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n",
            "WorkDir: /content/drive/My Drive/OP3_TRAINNING/step_008\n",
            "LogDir: /content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\n",
            "TfLogDir: /content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\n",
            "to_load_path: /content/drive/My Drive/OP3_TRAINNING/step_008/best\n",
            "AlgoLoadPath: /content/drive/My Drive/OP3_TRAINNING/step_008/best/a2c\n",
            "AlgoLoadPath: /content/drive/My Drive/OP3_TRAINNING/step_008/best/ddpg\n",
            "AlgoLoadPath: /content/drive/My Drive/OP3_TRAINNING/step_008/best/ppo\n",
            "AlgoLoadPath: /content/drive/My Drive/OP3_TRAINNING/step_008/best/sac\n",
            "AlgoLoadPath: /content/drive/My Drive/OP3_TRAINNING/step_008/best/td3\n"
          ]
        }
      ],
      "source": [
        "# Prepare to load data from google drive\n",
        "from google.colab import drive\n",
        "import datetime\n",
        "\n",
        "# CONNECT TO GOOGLE DRIVE\n",
        "gdrive_path = '/content/drive'\n",
        "drive.mount(gdrive_path)\n",
        "\n",
        "# DEFINE WORK DIRECTORY\n",
        "workDir = os.path.join(gdrive_path, 'My Drive', 'OP3_TRAINNING', current_step)\n",
        "print('WorkDir:', workDir)\n",
        "\n",
        "log_dir = os.path.join(workDir, datetime.datetime.now().strftime(\"%Y%m%d-%H%M%S\"))\n",
        "print('LogDir:', log_dir)\n",
        "\n",
        "# create folder if it doesn't exists\n",
        "if not os.path.exists(log_dir):\n",
        "  os.makedirs(log_dir)\n",
        "\n",
        "tf_log_dir = os.path.join(log_dir, 'tensorboard_logs')\n",
        "print('TfLogDir:', tf_log_dir)\n",
        "\n",
        "# create folder if it doesn't exists\n",
        "if not os.path.exists(tf_log_dir):\n",
        "  os.makedirs(tf_log_dir)\n",
        "\n",
        "# best models\n",
        "to_load_path = os.path.join(workDir, 'best')\n",
        "print('to_load_path:', to_load_path)\n",
        "algos = [\"a2c\", \"ddpg\", \"ppo\", \"sac\", \"td3\"]\n",
        "for algo in algos:\n",
        "  algo_load_path = os.path.join(to_load_path, algo)\n",
        "  print('AlgoLoadPath:', algo_load_path)\n",
        "  if not os.path.exists(algo_load_path):\n",
        "    os.makedirs(algo_load_path)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "collapsed": true,
        "id": "3Q0XgJntGtLW"
      },
      "outputs": [],
      "source": [
        "# clean content folder\n",
        "import os\n",
        "import shutil\n",
        "\n",
        "# location\n",
        "location = \"/content\"\n",
        "\n",
        "# directories\n",
        "dirs = [\"sample_data\"]\n",
        "\n",
        "for dir in dirs:\n",
        "    path = os.path.join(location, dir)\n",
        "    try:\n",
        "        shutil.rmtree(path)\n",
        "    except OSError as e:\n",
        "        print(\"Error: %s : %s\" % (path, e.strerror))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "ediC96n-xI2A",
        "outputId": "c3a82543-7d36-4504-c077-2a88d35078c3"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/\n",
            "The directory '/content/op3' does not exist - git clone\n",
            "Cloning into '/content/op3'...\n",
            "remote: Enumerating objects: 155, done.\u001b[K\n",
            "remote: Counting objects: 100% (155/155), done.\u001b[K\n",
            "remote: Compressing objects: 100% (116/116), done.\u001b[K\n",
            "remote: Total 155 (delta 51), reused 139 (delta 35), pack-reused 0 (from 0)\u001b[K\n",
            "Receiving objects: 100% (155/155), 14.62 MiB | 19.54 MiB/s, done.\n",
            "Resolving deltas: 100% (51/51), done.\n"
          ]
        }
      ],
      "source": [
        "# Install Darwin Model\n",
        "model_path = '/content/op3'\n",
        "%cd /\n",
        "\n",
        "if os.path.isdir(model_path):\n",
        "  print(f\"The directory '{model_path}' exists - git pull\")\n",
        "  %cd {model_path}\n",
        "  !git pull\n",
        "else:\n",
        "  print(f\"The directory '{model_path}' does not exist - git clone\")\n",
        "  !git clone https://github.com/Gianzanti/op3_model.git {model_path}\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "IQwSCDW1xRgF",
        "outputId": "95dcac89-a432-463c-b841-b550e0c879ee"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/\n",
            "Obtaining file:///content/op3\n",
            "  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n",
            "  Checking if build backend supports build_editable ... \u001b[?25l\u001b[?25hdone\n",
            "  Getting requirements to build editable ... \u001b[?25l\u001b[?25hdone\n",
            "  Preparing editable metadata (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: gymnasium>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from op3==0.1.13) (1.2.0)\n",
            "Requirement already satisfied: imageio>=2.37.0 in /usr/local/lib/python3.12/dist-packages (from op3==0.1.13) (2.37.0)\n",
            "Collecting mujoco>=3.3.5 (from op3==0.1.13)\n",
            "  Downloading mujoco-3.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (41 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m42.0/42.0 kB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting stable-baselines3 (from op3==0.1.13)\n",
            "  Downloading stable_baselines3-2.7.0-py3-none-any.whl.metadata (4.8 kB)\n",
            "Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.2.0->op3==0.1.13) (2.0.2)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.2.0->op3==0.1.13) (3.1.1)\n",
            "Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.2.0->op3==0.1.13) (4.15.0)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium>=1.2.0->op3==0.1.13) (0.0.4)\n",
            "Requirement already satisfied: pillow>=8.3.2 in /usr/local/lib/python3.12/dist-packages (from imageio>=2.37.0->op3==0.1.13) (11.3.0)\n",
            "Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from mujoco>=3.3.5->op3==0.1.13) (1.4.0)\n",
            "Requirement already satisfied: etils[epath] in /usr/local/lib/python3.12/dist-packages (from mujoco>=3.3.5->op3==0.1.13) (1.13.0)\n",
            "Collecting glfw (from mujoco>=3.3.5->op3==0.1.13)\n",
            "  Downloading glfw-2.10.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38.p39.p310.p311.p312.p313-none-manylinux_2_28_x86_64.whl.metadata (5.4 kB)\n",
            "Requirement already satisfied: pyopengl in /usr/local/lib/python3.12/dist-packages (from mujoco>=3.3.5->op3==0.1.13) (3.1.10)\n",
            "Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from stable-baselines3->op3==0.1.13) (2.8.0+cu126)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stable-baselines3->op3==0.1.13) (2.2.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from stable-baselines3->op3==0.1.13) (3.10.0)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (3.19.1)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (75.2.0)\n",
            "Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (1.13.3)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (3.5)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (3.1.6)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (2025.3.0)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.77)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.77)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.80)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (9.10.2.21)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.4.1)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (11.3.0.4)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (10.3.7.77)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (11.7.1.2)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.5.4.2)\n",
            "Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (0.7.1)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (2.27.3)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.77)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (12.6.85)\n",
            "Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (1.11.1.6)\n",
            "Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (3.4.0)\n",
            "Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from etils[epath]->mujoco>=3.3.5->op3==0.1.13) (6.5.2)\n",
            "Requirement already satisfied: zipp in /usr/local/lib/python3.12/dist-packages (from etils[epath]->mujoco>=3.3.5->op3==0.1.13) (3.23.0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (4.59.2)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (1.4.9)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (25.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (3.2.3)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable-baselines3->op3==0.1.13) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3->op3==0.1.13) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stable-baselines3->op3==0.1.13) (2025.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->stable-baselines3->op3==0.1.13) (1.17.0)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (1.3.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0,>=2.3->stable-baselines3->op3==0.1.13) (3.0.2)\n",
            "Downloading mujoco-3.3.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.7/6.7 MB\u001b[0m \u001b[31m43.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading stable_baselines3-2.7.0-py3-none-any.whl (187 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m187.2/187.2 kB\u001b[0m \u001b[31m24.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading glfw-2.10.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38.p39.p310.p311.p312.p313-none-manylinux_2_28_x86_64.whl (243 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m243.5/243.5 kB\u001b[0m \u001b[31m30.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: op3\n",
            "  Building editable for op3 (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for op3: filename=op3-0.1.13-py3-none-any.whl size=1157 sha256=89589c092e5817d0f4e02b3c78ec0f3f388bc83956dbb7c26d3083e375759ab4\n",
            "  Stored in directory: /tmp/pip-ephem-wheel-cache-u75dhfe5/wheels/6e/41/34/9ebb5c3b64ee3d5f174ea5b433d00e8f3478f5497c112a46b1\n",
            "Successfully built op3\n",
            "Installing collected packages: glfw, mujoco, stable-baselines3, op3\n",
            "Successfully installed glfw-2.10.0 mujoco-3.3.5 op3-0.1.13 stable-baselines3-2.7.0\n"
          ]
        }
      ],
      "source": [
        "%cd /\n",
        "!pip install -e {model_path}"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "GsDs_ja7xW9G",
        "outputId": "7b249298-05f2-48df-9ccf-aeb44bb861bc"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/\n",
            "The directory '/content/rl-zoo' does not exist - git clone\n",
            "Cloning into '/content/rl-zoo'...\n",
            "remote: Enumerating objects: 3683, done.\u001b[K\n",
            "remote: Counting objects: 100% (43/43), done.\u001b[K\n",
            "remote: Compressing objects: 100% (24/24), done.\u001b[K\n",
            "remote: Total 3683 (delta 33), reused 19 (delta 19), pack-reused 3640 (from 3)\u001b[K\n",
            "Receiving objects: 100% (3683/3683), 8.56 MiB | 7.73 MiB/s, done.\n",
            "Resolving deltas: 100% (2249/2249), done.\n"
          ]
        }
      ],
      "source": [
        "# Install RL Zoo\n",
        "trainner_path = '/content/rl-zoo'\n",
        "%cd /\n",
        "\n",
        "if os.path.isdir(trainner_path):\n",
        "  print(f\"The directory '{trainner_path}' exists - git pull\")\n",
        "  %cd {trainner_path}\n",
        "  !git pull\n",
        "else:\n",
        "  print(f\"The directory '{trainner_path}' does not exist - git clone\")\n",
        "  !git clone https://github.com/Gianzanti/rl-zoo.git {trainner_path}\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "a0CKEYmH0y6v",
        "outputId": "1f6ac3a0-43d1-4aa3-9b7c-04a5f17e3f93"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/\n",
            "Obtaining file:///content/rl-zoo\n",
            "  Installing build dependencies ... \u001b[?25l\u001b[?25hdone\n",
            "  Checking if build backend supports build_editable ... \u001b[?25l\u001b[?25hdone\n",
            "  Getting requirements to build editable ... \u001b[?25l\u001b[?25hdone\n",
            "  Preparing editable metadata (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting sb3_contrib<3.0,>=2.7.0 (from rl_zoo3==2.7.0)\n",
            "  Downloading sb3_contrib-2.7.0-py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: gymnasium<1.3.0,>=0.29.1 in /usr/local/lib/python3.12/dist-packages (from rl_zoo3==2.7.0) (1.2.0)\n",
            "Collecting huggingface_sb3<4.0,>=3.0 (from rl_zoo3==2.7.0)\n",
            "  Downloading huggingface_sb3-3.0-py3-none-any.whl.metadata (6.3 kB)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from rl_zoo3==2.7.0) (4.67.1)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from rl_zoo3==2.7.0) (13.9.4)\n",
            "Collecting optuna>=3.0 (from rl_zoo3==2.7.0)\n",
            "  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from rl_zoo3==2.7.0) (6.0.2)\n",
            "Collecting pytablewriter~=1.2 (from rl_zoo3==2.7.0)\n",
            "  Downloading pytablewriter-1.2.1-py3-none-any.whl.metadata (38 kB)\n",
            "Collecting shimmy~=2.0 (from rl_zoo3==2.7.0)\n",
            "  Downloading Shimmy-2.0.0-py3-none-any.whl.metadata (3.5 kB)\n",
            "Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium<1.3.0,>=0.29.1->rl_zoo3==2.7.0) (2.0.2)\n",
            "Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium<1.3.0,>=0.29.1->rl_zoo3==2.7.0) (3.1.1)\n",
            "Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from gymnasium<1.3.0,>=0.29.1->rl_zoo3==2.7.0) (4.15.0)\n",
            "Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from gymnasium<1.3.0,>=0.29.1->rl_zoo3==2.7.0) (0.0.4)\n",
            "Requirement already satisfied: huggingface-hub~=0.8 in /usr/local/lib/python3.12/dist-packages (from huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (0.34.4)\n",
            "Requirement already satisfied: wasabi in /usr/local/lib/python3.12/dist-packages (from huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (1.1.3)\n",
            "Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0->rl_zoo3==2.7.0) (1.16.5)\n",
            "Collecting colorlog (from optuna>=3.0->rl_zoo3==2.7.0)\n",
            "  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0->rl_zoo3==2.7.0) (25.0)\n",
            "Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna>=3.0->rl_zoo3==2.7.0) (2.0.43)\n",
            "Requirement already satisfied: setuptools>=38.3.0 in /usr/local/lib/python3.12/dist-packages (from pytablewriter~=1.2->rl_zoo3==2.7.0) (75.2.0)\n",
            "Collecting DataProperty<2,>=1.1.0 (from pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading DataProperty-1.1.0-py3-none-any.whl.metadata (11 kB)\n",
            "Collecting mbstrdecoder<2,>=1.0.0 (from pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading mbstrdecoder-1.1.4-py3-none-any.whl.metadata (4.3 kB)\n",
            "Collecting pathvalidate<4,>=2.3.0 (from pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)\n",
            "Collecting tabledata<2,>=1.3.1 (from pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading tabledata-1.3.4-py3-none-any.whl.metadata (3.7 kB)\n",
            "Collecting tcolorpy<1,>=0.0.5 (from pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading tcolorpy-0.1.7-py3-none-any.whl.metadata (6.3 kB)\n",
            "Collecting typepy<2,>=1.3.2 (from typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.7.0)\n",
            "  Downloading typepy-1.3.4-py3-none-any.whl.metadata (9.2 kB)\n",
            "Requirement already satisfied: stable_baselines3<3.0,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (2.7.0)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->rl_zoo3==2.7.0) (4.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->rl_zoo3==2.7.0) (2.19.2)\n",
            "Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna>=3.0->rl_zoo3==2.7.0) (1.3.10)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (3.19.1)\n",
            "Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (2025.3.0)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (2.32.4)\n",
            "Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (1.1.9)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->rl_zoo3==2.7.0) (0.1.2)\n",
            "Requirement already satisfied: chardet<6,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from mbstrdecoder<2,>=1.0.0->pytablewriter~=1.2->rl_zoo3==2.7.0) (5.2.0)\n",
            "Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna>=3.0->rl_zoo3==2.7.0) (3.2.4)\n",
            "Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.12/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (2.8.0+cu126)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (2.2.2)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (3.10.0)\n",
            "Requirement already satisfied: python-dateutil<3.0.0,>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.7.0) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2018.9 in /usr/local/lib/python3.12/dist-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.7.0) (2025.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.0->typepy[datetime]<2,>=1.3.2->pytablewriter~=1.2->rl_zoo3==2.7.0) (1.17.0)\n",
            "Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (1.13.3)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (3.5)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (3.1.6)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.77)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.77)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.80)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (9.10.2.21)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.4.1)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (11.3.0.4)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (10.3.7.77)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (11.7.1.2)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.5.4.2)\n",
            "Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (0.7.1)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (2.27.3)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.77)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (12.6.85)\n",
            "Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (1.11.1.6)\n",
            "Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (3.4.0)\n",
            "Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna>=3.0->rl_zoo3==2.7.0) (3.0.2)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (4.59.2)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (1.4.9)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (3.2.3)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (2025.2)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (3.4.3)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub~=0.8->huggingface_sb3<4.0,>=3.0->rl_zoo3==2.7.0) (2025.8.3)\n",
            "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0,>=2.3->stable_baselines3<3.0,>=2.7.0->sb3_contrib<3.0,>=2.7.0->rl_zoo3==2.7.0) (1.3.0)\n",
            "Downloading huggingface_sb3-3.0-py3-none-any.whl (9.7 kB)\n",
            "Downloading optuna-4.5.0-py3-none-any.whl (400 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m400.9/400.9 kB\u001b[0m \u001b[31m5.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pytablewriter-1.2.1-py3-none-any.whl (91 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m91.1/91.1 kB\u001b[0m \u001b[31m12.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading sb3_contrib-2.7.0-py3-none-any.whl (93 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m93.2/93.2 kB\u001b[0m \u001b[31m12.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading Shimmy-2.0.0-py3-none-any.whl (30 kB)\n",
            "Downloading DataProperty-1.1.0-py3-none-any.whl (27 kB)\n",
            "Downloading mbstrdecoder-1.1.4-py3-none-any.whl (7.9 kB)\n",
            "Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)\n",
            "Downloading tabledata-1.3.4-py3-none-any.whl (11 kB)\n",
            "Downloading tcolorpy-0.1.7-py3-none-any.whl (8.1 kB)\n",
            "Downloading typepy-1.3.4-py3-none-any.whl (31 kB)\n",
            "Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)\n",
            "Building wheels for collected packages: rl_zoo3\n",
            "  Building editable for rl_zoo3 (pyproject.toml) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for rl_zoo3: filename=rl_zoo3-2.7.0-0.editable-py3-none-any.whl size=4428 sha256=bdf11481701e4035fa61f94deb57410efd2fe2f5df6b9c966934068f3032e467\n",
            "  Stored in directory: /tmp/pip-ephem-wheel-cache-xd20kyd7/wheels/2d/0b/3c/be4c09b7d9d2a891b5d1bc1e086a8fe4f4b4f016a0613b625c\n",
            "Successfully built rl_zoo3\n",
            "Installing collected packages: tcolorpy, pathvalidate, mbstrdecoder, colorlog, typepy, shimmy, optuna, huggingface_sb3, DataProperty, tabledata, sb3_contrib, pytablewriter, rl_zoo3\n",
            "Successfully installed DataProperty-1.1.0 colorlog-6.9.0 huggingface_sb3-3.0 mbstrdecoder-1.1.4 optuna-4.5.0 pathvalidate-3.3.1 pytablewriter-1.2.1 rl_zoo3-2.7.0 sb3_contrib-2.7.0 shimmy-2.0.0 tabledata-1.3.4 tcolorpy-0.1.7 typepy-1.3.4\n"
          ]
        }
      ],
      "source": [
        "%cd /\n",
        "!pip install -e {trainner_path}"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "wZ-shVIX6QE3",
        "outputId": "997aa36e-3a12-4393-82df-50297c36f2e6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/rl-zoo\n",
            "Training: a2c\n",
            "python3 train.py --algo a2c --env DarwinOp3-v3 -conf research_config/a2c.yml -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" --tensorboard-log \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\" --save-freq 200000 --vec-env subproc --eval-freq 400000 --n-eval-envs 3 --eval-episodes 30 --env-kwargs keep_alive_weight:1.0 control_weight:0.0 target_distance:3.0 velocity_weight:3.0 reach_target_reward:100.0 knee_flex_weight:0.0 feet_up_weight:0.0 feet_misalign_weight:0.0 max_timestep:5000 --hyperparams n_envs:20 learning_rate:0.0007 n_timesteps:10000000 env_wrapper:\"[{'gymnasium.wrappers.TimeLimit': {'max_episode_steps': 5500}}]\" --device cpu -i /content/drive/My Drive/OP3_TRAINNING/step_008/best/a2c/best_model.zip -P\n",
            "2025-09-14 12:38:00.726076: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853480.746441    2461 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853480.752609    2461 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853480.768268    2461 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853480.768291    2461 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853480.768294    2461 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853480.768297    2461 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:00.772782: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.\n",
            "Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.\n",
            "See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.\n",
            "usage: train.py [-h]\n",
            "                [--algo {a2c,ddpg,dqn,ppo,sac,td3,ars,crossq,qrdqn,tqc,trpo,ppo_lstm}]\n",
            "                [--env ENV] [-tb TENSORBOARD_LOG] [-i TRAINED_AGENT]\n",
            "                [--truncate-last-trajectory TRUNCATE_LAST_TRAJECTORY]\n",
            "                [-n N_TIMESTEPS] [--num-threads NUM_THREADS]\n",
            "                [--log-interval LOG_INTERVAL] [--eval-freq EVAL_FREQ]\n",
            "                [--optimization-log-path OPTIMIZATION_LOG_PATH]\n",
            "                [--eval-episodes EVAL_EPISODES] [--n-eval-envs N_EVAL_ENVS]\n",
            "                [--save-freq SAVE_FREQ] [--save-replay-buffer] [-f LOG_FOLDER]\n",
            "                [--seed SEED] [--vec-env {dummy,subproc}] [--device DEVICE]\n",
            "                [--n-trials N_TRIALS] [--max-total-trials MAX_TOTAL_TRIALS]\n",
            "                [-optimize] [--no-optim-plots] [--n-jobs N_JOBS]\n",
            "                [--sampler {random,tpe,auto}] [--pruner {halving,median,none}]\n",
            "                [--n-startup-trials N_STARTUP_TRIALS]\n",
            "                [--n-evaluations N_EVALUATIONS] [--storage STORAGE]\n",
            "                [--study-name STUDY_NAME] [--trial-id TRIAL_ID]\n",
            "                [--verbose VERBOSE]\n",
            "                [--gym-packages GYM_PACKAGES [GYM_PACKAGES ...]]\n",
            "                [--env-kwargs ENV_KWARGS [ENV_KWARGS ...]]\n",
            "                [--eval-env-kwargs EVAL_ENV_KWARGS [EVAL_ENV_KWARGS ...]]\n",
            "                [-params HYPERPARAMS [HYPERPARAMS ...]] [-conf CONF_FILE]\n",
            "                [-uuid] [--track] [--wandb-project-name WANDB_PROJECT_NAME]\n",
            "                [--wandb-entity WANDB_ENTITY] [-P]\n",
            "                [-tags WANDB_TAGS [WANDB_TAGS ...]]\n",
            "train.py: error: unrecognized arguments: Drive/OP3_TRAINNING/step_008/best/a2c/best_model.zip\n",
            "python3 -m rl_zoo3.record_video --algo a2c --env DarwinOp3-v3 -n 3000 --load-best -o \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\"\n",
            "2025-09-14 12:38:10.420759: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853490.440470    2537 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853490.446563    2537 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853490.461581    2537 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853490.461605    2537 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853490.461608    2537 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853490.461610    2537 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:10.466455: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.\n",
            "Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.\n",
            "See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.\n",
            "Loading latest experiment, id=0\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 88, in _run_code\n",
            "  File \"/content/rl-zoo/rl_zoo3/record_video.py\", line 60, in <module>\n",
            "    name_prefix, model_path, log_path = get_model_path(\n",
            "                                        ^^^^^^^^^^^^^^^\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 488, in get_model_path\n",
            "    assert os.path.isdir(log_path), f\"The {log_path} folder was not found\"\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
            "AssertionError: The /content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/a2c folder was not found\n",
            "Training: ddpg\n",
            "python3 train.py --algo ddpg --env DarwinOp3-v3 -conf research_config/ddpg.yml -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" --tensorboard-log \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\" --save-freq 200000 --vec-env subproc --eval-freq 400000 --n-eval-envs 3 --eval-episodes 30 --env-kwargs keep_alive_weight:1.0 control_weight:0.0 target_distance:3.0 velocity_weight:3.0 reach_target_reward:100.0 knee_flex_weight:0.0 feet_up_weight:0.0 feet_misalign_weight:0.0 max_timestep:5000 --hyperparams n_envs:20 learning_rate:0.001 n_timesteps:10000000 env_wrapper:\"[{'gymnasium.wrappers.TimeLimit': {'max_episode_steps': 5500}}]\" --device cuda -i /content/drive/My Drive/OP3_TRAINNING/step_008/best/ddpg/best_model.zip -P\n",
            "2025-09-14 12:38:17.803694: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853497.823121    2593 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853497.829206    2593 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853497.844073    2593 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853497.844106    2593 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853497.844109    2593 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853497.844113    2593 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:17.848610: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 42, in tf\n",
            "    from tensorboard.compat import notf  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py)\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/pandas/__init__.py\", line 142, in <module>\n",
            "    from pandas.io.api import (\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/pandas/io/api.py\", line 38, in <module>\n",
            "    from pandas.io.xml import read_xml\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/pandas/io/xml.py\", line 864, in <module>\n",
            "    @doc(\n",
            "     ^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/pandas/util/_decorators.py\", line 367, in decorator\n",
            "    docstring_components.append(dedent(decorated.__doc__))\n",
            "                                ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.12/textwrap.py\", line 435, in dedent\n",
            "    text = _whitespace_only_re.sub('', text)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/rl-zoo/train.py\", line 1, in <module>\n",
            "    from rl_zoo3.train import train\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 7, in <module>\n",
            "    from stable_baselines3.common.buffers import RolloutBuffer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/buffers.py\", line 17, in <module>\n",
            "    from stable_baselines3.common.utils import get_device\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/utils.py\", line 22, in <module>\n",
            "    from torch.utils.tensorboard import SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/__init__.py\", line 12, in <module>\n",
            "    from .writer import FileWriter, SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/writer.py\", line 19, in <module>\n",
            "    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/_embedding.py\", line 10, in <module>\n",
            "    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, \"join\")\n",
            "                              ^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 65, in __getattr__\n",
            "    return getattr(load_once(self), attr_name)\n",
            "                   ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 97, in wrapper\n",
            "    cache[arg] = f(arg)\n",
            "                 ^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 50, in load_once\n",
            "    module = load_fn()\n",
            "             ^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 45, in tf\n",
            "    import tensorflow\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/__init__.py\", line 468, in <module>\n",
            "    importlib.import_module(\"keras.src.optimizers\")\n",
            "  File \"/usr/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/__init__.py\", line 7, in <module>\n",
            "    from keras import _tf_keras as _tf_keras\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/_tf_keras/__init__.py\", line 1, in <module>\n",
            "    from keras._tf_keras import keras\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/_tf_keras/keras/__init__.py\", line 7, in <module>\n",
            "    from keras import activations as activations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/activations/__init__.py\", line 7, in <module>\n",
            "    from keras.src.activations import deserialize as deserialize\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/__init__.py\", line 1, in <module>\n",
            "    from keras.src import activations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/activations/__init__.py\", line 34, in <module>\n",
            "    from keras.src.saving import object_registration\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/saving/__init__.py\", line 7, in <module>\n",
            "    from keras.src.saving.saving_api import load_model\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_api.py\", line 7, in <module>\n",
            "    from keras.src.legacy.saving import legacy_h5_format\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/legacy/saving/legacy_h5_format.py\", line 13, in <module>\n",
            "    from keras.src.legacy.saving import saving_utils\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/legacy/saving/saving_utils.py\", line 10, in <module>\n",
            "    from keras.src import models\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/__init__.py\", line 1, in <module>\n",
            "    from keras.src.models.functional import Functional\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/functional.py\", line 16, in <module>\n",
            "    from keras.src.models.model import Model\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/model.py\", line 12, in <module>\n",
            "    from keras.src.trainers import trainer as base_trainer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/trainer.py\", line 14, in <module>\n",
            "    from keras.src.trainers.data_adapters import data_adapter_utils\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/__init__.py\", line 4, in <module>\n",
            "    from keras.src.trainers.data_adapters import array_data_adapter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/array_data_adapter.py\", line 7, in <module>\n",
            "    from keras.src.trainers.data_adapters import array_slicing\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/array_slicing.py\", line 12, in <module>\n",
            "    import pandas\n",
            "  File \"<frozen importlib._bootstrap>\", line 1357, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 420, in __exit__\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "python3 -m rl_zoo3.record_video --algo ddpg --env DarwinOp3-v3 -n 3000 --load-best -o \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\"\n",
            "Exception ignored in: <function _get_module_lock.<locals>.cb at 0x790c8eb98e00>\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 454, in cb\n",
            "KeyboardInterrupt: \n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen runpy>\", line 189, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 112, in _get_module_details\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 3, in <module>\n",
            "    import torch as th\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/__init__.py\", line 2668, in <module>\n",
            "    from torch import _meta_registrations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py\", line 7862, in <module>\n",
            "    _create_binary_float_meta_func(aten.special_shifted_chebyshev_polynomial_w)\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py\", line 7834, in _create_binary_float_meta_func\n",
            "    @register_meta(func)\n",
            "     ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py\", line 68, in wrapper\n",
            "    pytree.tree_map_(register, op)\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/_pytree.py\", line 1413, in tree_map_\n",
            "    deque(map(func, *flat_args), maxlen=0)  # consume and exhaust the iterable\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py\", line 66, in register\n",
            "    _add_op_to_registry(meta_table, op, fn)\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_decomp/__init__.py\", line 81, in _add_op_to_registry\n",
            "    overloads.append(getattr(op, ol))\n",
            "                     ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_ops.py\", line 1214, in __getattr__\n",
            "    OpOverload(self, op_, op_dk_, schema, tags)\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_ops.py\", line 783, in __init__\n",
            "    self.__name__ = f\"{self._schema.name.split('::')[1]}.{self._overloadname}\"\n",
            "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "Training: ppo\n",
            "python3 train.py --algo ppo --env DarwinOp3-v3 -conf research_config/ppo.yml -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" --tensorboard-log \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\" --save-freq 200000 --vec-env subproc --eval-freq 400000 --n-eval-envs 3 --eval-episodes 30 --env-kwargs keep_alive_weight:1.0 control_weight:0.0 target_distance:3.0 velocity_weight:3.0 reach_target_reward:100.0 knee_flex_weight:0.0 feet_up_weight:0.0 feet_misalign_weight:0.0 max_timestep:5000 --hyperparams n_envs:20 learning_rate:0.0003 n_timesteps:10000000 env_wrapper:\"[{'gymnasium.wrappers.TimeLimit': {'max_episode_steps': 5500}}]\" --device cpu -i /content/drive/My Drive/OP3_TRAINNING/step_008/best/ppo/best_model.zip -P\n",
            "2025-09-14 12:38:24.334199: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853504.353886    2648 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853504.360076    2648 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853504.375284    2648 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853504.375308    2648 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853504.375311    2648 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853504.375314    2648 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:24.379957: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 42, in tf\n",
            "    from tensorboard.compat import notf  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py)\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/__init__.py\", line 4, in <module>\n",
            "    from keras.src.trainers.data_adapters import array_data_adapter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/array_data_adapter.py\", line 7, in <module>\n",
            "    from keras.src.trainers.data_adapters import array_slicing\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/array_slicing.py\", line 12, in <module>\n",
            "    import pandas\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/pandas/__init__.py\", line 116, in <module>\n",
            "    from pandas.tseries.api import infer_freq\n",
            "  File \"<frozen importlib._bootstrap>\", line 1357, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 417, in __enter__\n",
            "  File \"<frozen importlib._bootstrap>\", line 456, in _get_module_lock\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/rl-zoo/train.py\", line 1, in <module>\n",
            "    from rl_zoo3.train import train\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 7, in <module>\n",
            "    from stable_baselines3.common.buffers import RolloutBuffer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/buffers.py\", line 17, in <module>\n",
            "    from stable_baselines3.common.utils import get_device\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/utils.py\", line 22, in <module>\n",
            "    from torch.utils.tensorboard import SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/__init__.py\", line 12, in <module>\n",
            "    from .writer import FileWriter, SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/writer.py\", line 19, in <module>\n",
            "    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/_embedding.py\", line 10, in <module>\n",
            "    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, \"join\")\n",
            "                              ^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 65, in __getattr__\n",
            "    return getattr(load_once(self), attr_name)\n",
            "                   ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 97, in wrapper\n",
            "    cache[arg] = f(arg)\n",
            "                 ^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 50, in load_once\n",
            "    module = load_fn()\n",
            "             ^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 45, in tf\n",
            "    import tensorflow\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/__init__.py\", line 468, in <module>\n",
            "    importlib.import_module(\"keras.src.optimizers\")\n",
            "  File \"/usr/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
            "    return _bootstrap._gcd_import(name[level:], package, level)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/__init__.py\", line 7, in <module>\n",
            "    from keras import _tf_keras as _tf_keras\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/_tf_keras/__init__.py\", line 1, in <module>\n",
            "    from keras._tf_keras import keras\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/_tf_keras/keras/__init__.py\", line 7, in <module>\n",
            "    from keras import activations as activations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/activations/__init__.py\", line 7, in <module>\n",
            "    from keras.src.activations import deserialize as deserialize\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/__init__.py\", line 1, in <module>\n",
            "    from keras.src import activations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/activations/__init__.py\", line 34, in <module>\n",
            "    from keras.src.saving import object_registration\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/saving/__init__.py\", line 7, in <module>\n",
            "    from keras.src.saving.saving_api import load_model\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_api.py\", line 7, in <module>\n",
            "    from keras.src.legacy.saving import legacy_h5_format\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/legacy/saving/legacy_h5_format.py\", line 13, in <module>\n",
            "    from keras.src.legacy.saving import saving_utils\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/legacy/saving/saving_utils.py\", line 10, in <module>\n",
            "    from keras.src import models\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/__init__.py\", line 1, in <module>\n",
            "    from keras.src.models.functional import Functional\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/functional.py\", line 16, in <module>\n",
            "    from keras.src.models.model import Model\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/models/model.py\", line 12, in <module>\n",
            "    from keras.src.trainers import trainer as base_trainer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/keras/src/trainers/trainer.py\", line 14, in <module>\n",
            "    from keras.src.trainers.data_adapters import data_adapter_utils\n",
            "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1334, in _find_and_load_unlocked\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "python3 -m rl_zoo3.record_video --algo ppo --env DarwinOp3-v3 -n 3000 --load-best -o \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\"\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 3, in <module>\n",
            "    import torch as th\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/__init__.py\", line 2668, in <module>\n",
            "    from torch import _meta_registrations\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py\", line 13, in <module>\n",
            "    from torch._decomp import (\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_decomp/__init__.py\", line 276, in <module>\n",
            "    import torch._decomp.decompositions\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_decomp/decompositions.py\", line 16, in <module>\n",
            "    import torch._prims as prims\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_prims/__init__.py\", line 936, in <module>\n",
            "    tan = _make_elementwise_unary_prim(\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_prims/__init__.py\", line 493, in _make_elementwise_unary_prim\n",
            "    return _make_prim(\n",
            "           ^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_prims/__init__.py\", line 321, in _make_prim\n",
            "    prim_def = torch.library.custom_op(\n",
            "               ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py\", line 174, in custom_op\n",
            "    return inner(fn)\n",
            "           ^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py\", line 155, in inner\n",
            "    result = CustomOpDef(namespace, opname, schema_str, fn, tags)\n",
            "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py\", line 213, in __init__\n",
            "    self._register_to_dispatcher(self._tags)\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py\", line 636, in _register_to_dispatcher\n",
            "    autograd_impl = autograd.make_autograd_impl(self._opoverload, self)\n",
            "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/_library/autograd.py\", line 29, in make_autograd_impl\n",
            "    class Metadata:\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen runpy>\", line 189, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 112, in _get_module_details\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<frozen importlib._bootstrap>\", line 1357, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 420, in __exit__\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "Training: sac\n",
            "python3 train.py --algo sac --env DarwinOp3-v3 -conf research_config/sac.yml -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" --tensorboard-log \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\" --save-freq 200000 --vec-env subproc --eval-freq 400000 --n-eval-envs 3 --eval-episodes 30 --env-kwargs keep_alive_weight:1.0 control_weight:0.0 target_distance:3.0 velocity_weight:3.0 reach_target_reward:100.0 knee_flex_weight:0.0 feet_up_weight:0.0 feet_misalign_weight:0.0 max_timestep:5000 --hyperparams n_envs:20 learning_rate:0.0003 n_timesteps:10000000 env_wrapper:\"[{'gymnasium.wrappers.TimeLimit': {'max_episode_steps': 5500}}]\" --device cuda -i /content/drive/My Drive/OP3_TRAINNING/step_008/best/sac/best_model.zip -P\n",
            "2025-09-14 12:38:30.900545: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853510.919985    2703 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853510.925792    2703 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853510.940737    2703 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853510.940761    2703 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853510.940764    2703 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853510.940766    2703 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:30.945096: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 42, in tf\n",
            "    from tensorboard.compat import notf  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py)\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/__init__.py\", line 49, in <module>\n",
            "    from tensorflow._api.v2 import __internal__\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/__internal__/__init__.py\", line 8, in <module>\n",
            "    from tensorflow._api.v2.__internal__ import autograph\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py\", line 9, in <module>\n",
            "    from tensorflow.python.autograph.impl.api import tf_convert # line: 493\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/python/autograph/impl/api.py\", line 27, in <module>\n",
            "    from tensorflow.python.autograph.converters import asserts\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/python/autograph/converters/asserts.py\", line 19, in <module>\n",
            "    from tensorflow.python.autograph.core import converter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/python/autograph/core/converter.py\", line 231, in <module>\n",
            "    class ProgramContext(object):\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/rl-zoo/train.py\", line 1, in <module>\n",
            "    from rl_zoo3.train import train\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 7, in <module>\n",
            "    from stable_baselines3.common.buffers import RolloutBuffer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/buffers.py\", line 17, in <module>\n",
            "    from stable_baselines3.common.utils import get_device\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/utils.py\", line 22, in <module>\n",
            "    from torch.utils.tensorboard import SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/__init__.py\", line 12, in <module>\n",
            "    from .writer import FileWriter, SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/writer.py\", line 19, in <module>\n",
            "    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/_embedding.py\", line 10, in <module>\n",
            "    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, \"join\")\n",
            "                              ^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 65, in __getattr__\n",
            "    return getattr(load_once(self), attr_name)\n",
            "                   ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 97, in wrapper\n",
            "    cache[arg] = f(arg)\n",
            "                 ^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 50, in load_once\n",
            "    module = load_fn()\n",
            "             ^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 45, in tf\n",
            "    import tensorflow\n",
            "  File \"<frozen importlib._bootstrap>\", line 1357, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 420, in __exit__\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "python3 -m rl_zoo3.record_video --algo sac --env DarwinOp3-v3 -n 3000 --load-best -o \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\"\n",
            "2025-09-14 12:38:33.515939: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
            "E0000 00:00:1757853513.535833    2723 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "E0000 00:00:1757853513.541937    2723 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "W0000 00:00:1757853513.557279    2723 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853513.557306    2723 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853513.557310    2723 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "W0000 00:00:1757853513.557314    2723 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.\n",
            "2025-09-14 12:38:33.562028: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "Exception ignored in: <function _xla_gc_callback at 0x7a453059ce00>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/lib/__init__.py\", line 96, in _xla_gc_callback\n",
            "    def _xla_gc_callback(*args):\n",
            "    \n",
            "KeyboardInterrupt: \n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 42, in tf\n",
            "    from tensorboard.compat import notf  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py)\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen runpy>\", line 189, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 112, in _get_module_details\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 7, in <module>\n",
            "    from stable_baselines3.common.buffers import RolloutBuffer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/buffers.py\", line 17, in <module>\n",
            "    from stable_baselines3.common.utils import get_device\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/utils.py\", line 22, in <module>\n",
            "    from torch.utils.tensorboard import SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/__init__.py\", line 12, in <module>\n",
            "    from .writer import FileWriter, SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/writer.py\", line 19, in <module>\n",
            "    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/_embedding.py\", line 10, in <module>\n",
            "    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, \"join\")\n",
            "                              ^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 65, in __getattr__\n",
            "    return getattr(load_once(self), attr_name)\n",
            "                   ^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 97, in wrapper\n",
            "    cache[arg] = f(arg)\n",
            "                 ^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/lazy.py\", line 50, in load_once\n",
            "    module = load_fn()\n",
            "             ^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/__init__.py\", line 45, in tf\n",
            "    import tensorflow\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/__init__.py\", line 55, in <module>\n",
            "    from tensorflow._api.v2 import compat\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/__init__.py\", line 8, in <module>\n",
            "    from tensorflow._api.v2.compat import v1\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py\", line 30, in <module>\n",
            "    from tensorflow._api.v2.compat.v1 import compat\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py\", line 8, in <module>\n",
            "    from tensorflow._api.v2.compat.v1.compat import v1\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py\", line 47, in <module>\n",
            "    from tensorflow._api.v2.compat.v1 import lite\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py\", line 9, in <module>\n",
            "    from tensorflow._api.v2.compat.v1.lite import experimental\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py\", line 8, in <module>\n",
            "    from tensorflow._api.v2.compat.v1.lite.experimental import authoring\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py\", line 8, in <module>\n",
            "    from tensorflow.lite.python.authoring.authoring import compatible # line: 263\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/authoring/authoring.py\", line 42, in <module>\n",
            "    from tensorflow.lite.python import convert\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/convert.py\", line 31, in <module>\n",
            "    from tensorflow.lite.python import util\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/util.py\", line 53, in <module>\n",
            "    from jax import jit as _jit\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/__init__.py\", line 83, in <module>\n",
            "    from jax._src.api import effects_barrier as effects_barrier\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/api.py\", line 47, in <module>\n",
            "    from jax._src import dispatch\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/dispatch.py\", line 31, in <module>\n",
            "    from jax._src import array\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/array.py\", line 37, in <module>\n",
            "    from jax._src.interpreters import pxla\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/interpreters/pxla.py\", line 56, in <module>\n",
            "    from jax._src.interpreters import batching\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/jax/_src/interpreters/batching.py\", line 62, in <module>\n",
            "    @dataclasses.dataclass(frozen=True)\n",
            "     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.12/dataclasses.py\", line 1265, in wrap\n",
            "    return _process_class(cls, init, repr, eq, order, unsafe_hash,\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.12/dataclasses.py\", line 1114, in _process_class\n",
            "    for fn in _frozen_get_del_attr(cls, field_list, globals):\n",
            "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.12/dataclasses.py\", line 644, in _frozen_get_del_attr\n",
            "    return (_create_fn('__setattr__',\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/lib/python3.12/dataclasses.py\", line 473, in _create_fn\n",
            "    exec(txt, globals, ns)\n",
            "  File \"<string>\", line 0, in <module>\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "Training: td3\n",
            "python3 train.py --algo td3 --env DarwinOp3-v3 -conf research_config/td3.yml -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" --tensorboard-log \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311/tensorboard_logs\" --save-freq 200000 --vec-env subproc --eval-freq 400000 --n-eval-envs 3 --eval-episodes 30 --env-kwargs keep_alive_weight:1.0 control_weight:0.0 target_distance:3.0 velocity_weight:3.0 reach_target_reward:100.0 knee_flex_weight:0.0 feet_up_weight:0.0 feet_misalign_weight:0.0 max_timestep:5000 --hyperparams n_envs:20 learning_rate:0.001 n_timesteps:10000000 env_wrapper:\"[{'gymnasium.wrappers.TimeLimit': {'max_episode_steps': 5500}}]\" --device cuda -i /content/drive/My Drive/OP3_TRAINNING/step_008/best/td3/best_model.zip -P\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/rl-zoo/train.py\", line 1, in <module>\n",
            "    from rl_zoo3.train import train\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 3, in <module>\n",
            "    import torch as th\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/__init__.py\", line 416, in <module>\n",
            "    from torch._C import *  # noqa: F403\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"<frozen importlib._bootstrap>\", line 463, in _lock_unlock_module\n",
            "KeyboardInterrupt\n",
            "^C\n",
            "python3 -m rl_zoo3.record_video --algo td3 --env DarwinOp3-v3 -n 3000 --load-best -o \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\" -f \"/content/drive/My Drive/OP3_TRAINNING/step_008/20250914-123311\"\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
            "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
            "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/absl/flags/_validators_classes.py\", line 21, in <module>\n",
            "    from absl.flags import _exceptions\n",
            "  File \"<frozen importlib._bootstrap>\", line 469, in _lock_unlock_module\n",
            "  File \"<frozen importlib._bootstrap>\", line 458, in _get_module_lock\n",
            "KeyboardInterrupt\n",
            "\n",
            "During handling of the above exception, another exception occurred:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"<frozen runpy>\", line 189, in _run_module_as_main\n",
            "  File \"<frozen runpy>\", line 112, in _get_module_details\n",
            "  File \"/content/rl-zoo/rl_zoo3/__init__.py\", line 9, in <module>\n",
            "    from rl_zoo3.utils import (\n",
            "  File \"/content/rl-zoo/rl_zoo3/utils.py\", line 9, in <module>\n",
            "    import stable_baselines3 as sb3  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/__init__.py\", line 3, in <module>\n",
            "    from stable_baselines3.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/__init__.py\", line 1, in <module>\n",
            "    from stable_baselines3.a2c.a2c import A2C\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/a2c/a2c.py\", line 7, in <module>\n",
            "    from stable_baselines3.common.buffers import RolloutBuffer\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/buffers.py\", line 17, in <module>\n",
            "    from stable_baselines3.common.utils import get_device\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/stable_baselines3/common/utils.py\", line 22, in <module>\n",
            "    from torch.utils.tensorboard import SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/__init__.py\", line 12, in <module>\n",
            "    from .writer import FileWriter, SummaryWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/torch/utils/tensorboard/writer.py\", line 16, in <module>\n",
            "    from tensorboard.summary.writer.event_file_writer import EventFileWriter\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/summary/__init__.py\", line 22, in <module>\n",
            "    from tensorboard.summary import v1  # noqa: F401\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/summary/v1.py\", line 23, in <module>\n",
            "    from tensorboard.plugins.histogram import summary as _histogram_summary\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/plugins/histogram/summary.py\", line 35, in <module>\n",
            "    from tensorboard.plugins.histogram import summary_v2\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/plugins/histogram/summary_v2.py\", line 35, in <module>\n",
            "    from tensorboard.util import tensor_util\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/util/tensor_util.py\", line 20, in <module>\n",
            "    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/tensorflow_stub/__init__.py\", line 25, in <module>\n",
            "    from . import app  # noqa\n",
            "    ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/tensorflow_stub/app.py\", line 21, in <module>\n",
            "    from . import flags\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/tensorboard/compat/tensorflow_stub/flags.py\", line 25, in <module>\n",
            "    from absl.flags import *  # pylint: disable=wildcard-import\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/absl/flags/__init__.py\", line 36, in <module>\n",
            "    from absl.flags import _defines\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/absl/flags/_defines.py\", line 26, in <module>\n",
            "    from absl.flags import _flagvalues\n",
            "  File \"/usr/local/lib/python3.12/dist-packages/absl/flags/_flagvalues.py\", line 31, in <module>\n",
            "    from absl.flags import _validators_classes\n",
            "  File \"<frozen importlib._bootstrap>\", line 1357, in _find_and_load\n",
            "  File \"<frozen importlib._bootstrap>\", line 420, in __exit__\n",
            "KeyboardInterrupt\n",
            "^C\n"
          ]
        }
      ],
      "source": [
        "%cd {trainner_path}\n",
        "\n",
        "algos = {\n",
        "  \"a2c\": {\n",
        "    \"lr\": 7e-4, \"dev\": \"cpu\"\n",
        "  },\n",
        "  'ddpg': {\n",
        "    'lr': 1e-3, 'dev': 'cuda'\n",
        "  },\n",
        "  'ppo': {\n",
        "    'lr': 3e-4, 'dev': 'cpu'\n",
        "  },\n",
        "  'sac': {\n",
        "    'lr': 3e-4, 'dev': 'cuda'\n",
        "  },\n",
        "  'td3': {\n",
        "    'lr': 1e-3, 'dev': 'cuda'\n",
        "  }\n",
        "}\n",
        "\n",
        "n_timestep = 10_000_000\n",
        "save_freq = min(200_000, int(n_timestep / 10))\n",
        "eval_freq = min(400_000, int(n_timestep / 10))\n",
        "max_episode_steps = 5500\n",
        "wrapper = [{\"gymnasium.wrappers.TimeLimit\": {\"max_episode_steps\": max_episode_steps}}]\n",
        "n_envs = 20\n",
        "n_eval_envs = 3\n",
        "eval_episodes = 30\n",
        "\n",
        "\n",
        "# weights\n",
        "keep_alive_weight = 1.0\n",
        "control_weight = 0.00 #1e-3\n",
        "target_distance = 3.0\n",
        "velocity_weight = 3.00 #3.0\n",
        "reach_target_reward = 100.0\n",
        "knee_flex_weight = 0.00 #1e-3\n",
        "feet_up_weight = 0.00 #1e-3\n",
        "feet_misalign_weight = 0.00 #0.5\n",
        "max_timestep = 5000\n",
        "\n",
        "\n",
        "# keep_alive_weight: float = 1.0,\n",
        "# control_weight: float = 1e-3,\n",
        "# target_distance: float = 100.0,\n",
        "# velocity_weight: float = 3.0,\n",
        "# reach_target_reward: float = 100.0,\n",
        "# knee_flex_weight: float = 1e-3,\n",
        "# feet_up_weight: float = 1e-3,\n",
        "# feet_misalign_weight: float = 0.05,\n",
        "\n",
        "for algo, value in algos.items():\n",
        "  print('Training:', algo)\n",
        "  config = f'research_config/{algo}.yml'\n",
        "  best = os.path.join(to_load_path, algo, 'best_model.zip')\n",
        "  if not os.path.exists(best):\n",
        "    best = ''\n",
        "  else:\n",
        "    best = f'-i \"{best}\"'\n",
        "\n",
        "  train_cmd = f'python3 train.py --algo {algo} --env DarwinOp3-v3 -conf {config} \\\n",
        "-f \"{log_dir}\" --tensorboard-log \"{tf_log_dir}\" --save-freq {save_freq} \\\n",
        "--vec-env subproc --eval-freq {eval_freq} --n-eval-envs {n_eval_envs} --eval-episodes {eval_episodes} \\\n",
        "--env-kwargs keep_alive_weight:{keep_alive_weight} control_weight:{control_weight} \\\n",
        "target_distance:{target_distance} velocity_weight:{velocity_weight} \\\n",
        "reach_target_reward:{reach_target_reward} knee_flex_weight:{knee_flex_weight} \\\n",
        "feet_up_weight:{feet_up_weight} feet_misalign_weight:{feet_misalign_weight} \\\n",
        "max_timestep:{max_timestep} --hyperparams n_envs:{n_envs} learning_rate:{value[\"lr\"]} \\\n",
        "n_timesteps:{n_timestep} env_wrapper:\"{wrapper}\" --device {value[\"dev\"]} {best} -P'\n",
        "\n",
        "  print(train_cmd)\n",
        "  !{train_cmd}\n",
        "\n",
        "  video_cmd = f'python3 -m rl_zoo3.record_video --algo {algo} \\\n",
        "--env DarwinOp3-v3 -n 3000 --load-best -o \"{log_dir}\" -f \"{log_dir}\"'\n",
        "  print(video_cmd)\n",
        "  !{video_cmd}\n"
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "gpuType": "T4",
      "machine_shape": "hm",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}